version: "3"
services:
  bd:
    image: postgres
    container_name: db-container
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_persistence:/var/lib/postgresql/data
volumes:
  db_persistence: